### ISSUE TITLE
Theme doesn't work with hexo 2.8.3

### ISSUE THREAD

**Issue by codepreneur** [jaredly/hexium#3]
When I `git clone git@github.com:jaredly/hexium.git themes/hexium` then change `theme` to `hexium` in `_config.yml` and then `hexo server` when I go to the browser I get:

```
{{! Document Settings }} {{! Page Meta }} {{! Styles'n'Scripts }} {{! Ghost outputs important style and meta data with this tag }} {{ghost_head}} {{! Everything else gets inserted here }} {{{body}}} {{! Ghost outputs important scripts and data with this tag }} {{ghost_foot}} {{! The main JavaScript file for Casper }} {{#if theme.ga_id}} {{/if}}
```

If I then do `npm install hexo-renderer-handlebars --save` I get :

```
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/johndoe/test-hexo/themes/hexium/helper/index.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

If I then `npm i moment --save` then I get:

```
TypeError: Cannot read property 'slice' of undefined
    at Object.module.exports.asset (/Users/johndoe/test-hexo/themes/hexium/helper/index.js:19:13)
    at Object.eval (eval at <anonymous> (/Users/johndoe/test-hexo/node_modules/hexo-renderer-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:43:222)
    at /Users/johndoe/test-hexo/node_modules/hexo-renderer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:86:31
    at /Users/johndoe/test-hexo/node_modules/hexo-renderer-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:465:21
    at handlebarsRenderer (/Users/johndoe/test-hexo/node_modules/hexo-renderer-handlebars/index.js:32:10)
    at Domain.<anonymous> (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:78:38)
    at Domain.run (domain.js:197:16)
    at store.(anonymous function) (/usr/local/lib/node_modules/hexo/lib/extend/renderer.js:77:9)
    at /usr/local/lib/node_modules/hexo/lib/core/render.js:96:9
    at fn (/usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:641:34)
```

Help :)
